# Generated by Django 3.0 on 2020-01-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ImageField(null=True, upload_to='memes')),
                ('insert_text_x', models.IntegerField()),
                ('insert_text_y', models.IntegerField()),
            ],
        ),
    ]
