version: '3'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=motivator
      - POSTGRES_DB=motivator
      - POSTGRES_PASSWORD=motivator
    ports:
      - "5432:5432"
  web:
    build: .
    image: motivator
    env_file:
      - .envfile
    environment:
      - DJANGO_SETTINGS_MODULE=motivator.settings.development
    ports:
      - "8000:8000"
    volumes:
    - .:/motivator
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  celery:
    build: .
    env_file:
      - .envfile
    environment:
      - DJANGO_SETTINGS_MODULE=motivator.settings.development
    depends_on:
      - db
      - redis
    command: celery -A motivator worker -l info
    volumes:
      - .:/motivator
  celery-beat:
    build: .
    env_file:
      - .envfile
    environment:
      - DJANGO_SETTINGS_MODULE=motivator.settings.development
    command: celery -A motivator beat -l info
    volumes:
      - .:/motivator
    depends_on:
      - celery
      - db
      - redis

volumes:
  postgres_data: